{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "abc69be8",
   "metadata": {},
   "source": [
    "# Credit Card Details "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b122b99b",
   "metadata": {},
   "source": [
    "# For all the benefits of each credit card in a single cell of Excel sheet "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "54e2ae22",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Card Name: Platinum Credit Card\n",
      "Joining Fee: NIL\n",
      "Annual Fee: NIL\n",
      "\t\n",
      "Benefits of The Card: Zero Joining and Annual Fees;2 Rewards Points per Rs. 100 spent, except Fuel;1% Fuel Surcharge waiver at HPCL petrol pumps\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Coral Credit Card\n",
      "Joining Fee: ₹500/ NIL\n",
      "Annual Fee: ₹500/ NIL\n",
      "\t\n",
      "Benefits of The Card: 25% discount on movie tickets, on BookMyShow and Inox, twice per month;One Complimentary Railway and Domestic Airport Lounge Access, per quarter;1% Fuel Surcharge waiver at HPCL Petrol Pumps\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Rubyx Credit Card\n",
      "Joining Fee: ₹3000+GST\n",
      "Annual Fee: ₹2000+GST\n",
      "\t\n",
      "Benefits of The Card: Welcome vouchers worth Rs. 5000+;25% discount on movie tickets, on BookMyShow and Inox, twice per month;Air Accident insurance of Rs 1 cr and lost card liability Rs 50k;Two Complimentary rounds of golf, per month\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Sapphiro Credit Card\n",
      "Joining Fee: ₹6500+GST\n",
      "Annual Fee: ₹3500+GST\n",
      "\t\n",
      "Benefits of The Card: Welcome vouchers worth Rs. 9000+;Buy one movie ticket, get Rs 500 off on second tikcet, on BookMyShow, twice per month;Two Complimentary International Airport Lounge Access, per year;Four Complimentary Domestic Airport Lounge Access, per quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Manchester United Platinum Credit Card\n",
      "Joining Fee: ₹499+GST\n",
      "Annual Fee: ₹499+GST\n",
      "\t\n",
      "Benefits of The Card: Complimentary Manchester United Football;Up to 3 reward points per Rs. 100 spent;25% off up to Rs. 100 on selected cinema ticket retailers;1 Complimentary Airport Lounge Access per quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Manchester United Signature Credit Card\n",
      "Joining Fee: ₹2499+GST\n",
      "Annual Fee: ₹2499+GST/\n",
      "\t\n",
      "Benefits of The Card: Complimentary Manchester United Football & Holdall;Up to 5 reward points per Rs. 100 spent;25% off up to Rs. 150 on selected cinema ticket retailers;Two Complimentary Airport Lounge Access/quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Chennai Super Kings Credit Card\n",
      "Joining Fee: ₹500 + (GST)\n",
      "Card Name: MakeMyTrip ICICI Bank Platinum Credit Card\n",
      "Joining Fee: ₹500+Gst\n",
      "Annual Fee: Nil\n",
      "\t\n",
      "Benefits of The Card: Complimentary Manchester United Football & Holdall;Up to 5 reward points per Rs. 100 spent;25% off up to Rs. 150 on selected cinema ticket retailers;Two Complimentary Airport Lounge Access/quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: MakeMyTrip ICICI Bank Signature Credit Card\n",
      "Joining Fee: ₹2500+Gst\n",
      "Annual Fee: Nil\n",
      "\t\n",
      "Benefits of The Card: Complimentary Manchester United Football & Holdall;Up to 5 reward points per Rs. 100 spent;25% off up to Rs. 150 on selected cinema ticket retailers;Two Complimentary Airport Lounge Access/quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Expressions Card\n",
      "Joining Fee: ₹499 + GST\n",
      "Annual Fee: ₹499 + GST\n",
      "\t\n",
      "Benefits of The Card: Complimentary Manchester United Football & Holdall;Up to 5 reward points per Rs. 100 spent;25% off up to Rs. 150 on selected cinema ticket retailers;Two Complimentary Airport Lounge Access/quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: HPCL Coral Visa Card\n",
      "Joining Fee: ₹199+GST\n",
      "Annual Fee: ₹199+GST\n",
      "\t\n",
      "Benefits of The Card: Complimentary Manchester United Football & Holdall;Up to 5 reward points per Rs. 100 spent;25% off up to Rs. 150 on selected cinema ticket retailers;Two Complimentary Airport Lounge Access/quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: HPCL Super Saver Credit Card\n",
      "Joining Fee: ₹500+GST\n",
      "Annual Fee: ₹ 500+GST\n",
      "\t\n",
      "Benefits of The Card: Complimentary Manchester United Football & Holdall;Up to 5 reward points per Rs. 100 spent;25% off up to Rs. 150 on selected cinema ticket retailers;Two Complimentary Airport Lounge Access/quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Emirates\n",
      "Joining Fee: ₹ 10,000+GST\n",
      "Annual Fee: ₹ 10,000+GST\n",
      "\t\n",
      "Benefits of The Card: Complimentary Manchester United Football & Holdall;Up to 5 reward points per Rs. 100 spent;25% off up to Rs. 150 on selected cinema ticket retailers;Two Complimentary Airport Lounge Access/quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Accelero\n",
      "Joining Fee: ₹ 499+GST\n",
      "Annual Fee: ₹ 499+GST\n",
      "\t\n",
      "Benefits of The Card: Complimentary Manchester United Football & Holdall;Up to 5 reward points per Rs. 100 spent;25% off up to Rs. 150 on selected cinema ticket retailers;Two Complimentary Airport Lounge Access/quarter\n",
      "\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Import necessary libraries\n",
    "import pandas as pd\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import openpyxl\n",
    "from datetime import datetime\n",
    "\n",
    "# Load existing data (if any)\n",
    "try:\n",
    "    existing_data = pd.read_excel('Credit.xlsx')\n",
    "except FileNotFoundError:\n",
    "    existing_data = pd.DataFrame(columns=['Card Name', 'Joining Fee', 'Annual Fee', 'Benefits of The Card'])\n",
    "\n",
    "# Create/Open workbook\n",
    "excel = openpyxl.Workbook()\n",
    "sheet = excel.active\n",
    "sheet.title = \"Credit Cards\"\n",
    "sheet.append(['Card Name', 'Joining Fee', 'Annual Fee', 'Benefits of The Card'])\n",
    "\n",
    "# Function to scrape credit card data\n",
    "def scrape_credit_cards():\n",
    "    # Source URL of the bank's credit card page\n",
    "    source = requests.get('https://www.icicibank.com/card/credit-cards/credit-card')\n",
    "    source.raise_for_status()\n",
    "    soup = BeautifulSoup(source.text, 'html.parser')\n",
    "\n",
    "    cards = soup.find('div', class_='compare-account account-variants-single-card').find_all('div', class_='account-variants-card-with-img')\n",
    "\n",
    "    # Timestamp for the current scraping session\n",
    "    timestamp = datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
    "    new_cards = []\n",
    "\n",
    "    for card in cards:\n",
    "        #Find the title element for the card\n",
    "        card_name_elem = card.find('div', class_='titie-wrapper')\n",
    "        #Find the joining fee for the card\n",
    "        card_join_fee = card.find('span', class_=\"joining-fee\").strong.text\n",
    "        #finding benefits of card\n",
    "        benefits_tags = card.find('ul').find_all('li')\n",
    "        if card_name_elem is not None:\n",
    "            #Find the card name if it is in an h3 tag\n",
    "            card_name_h3 = card_name_elem.find('h3')\n",
    "            if card_name_h3 is not None:\n",
    "                card_name = card_name_h3.text.strip()\n",
    "                print('Card Name:',card_name)\n",
    "                print('Joining Fee:',card_join_fee)\n",
    "                card_annual_fee = card.find('span',class_=\"line\").strong\n",
    "                if card_annual_fee is not None:\n",
    "                    print('Annual Fee:',card_annual_fee.text)\n",
    "                    print('\\t')  \n",
    "                else:\n",
    "                    continue\n",
    "                # Join the benefits tags using ';' as a delimiter\n",
    "                benefits = ';'.join([tag.text for tag in benefits_tags])\n",
    "                print('Benefits of The Card:', benefits)\n",
    "                print('\\n\\n')\n",
    "                # Check if the card is already in the existing data\n",
    "                if card_name not in existing_data['Card Name'].values:\n",
    "                    new_cards.append([card_name, card_join_fee, card_annual_fee.text, benefits])\n",
    "               \n",
    "            else:\n",
    "                #Find the card name if it is in an h4 tag\n",
    "                card_name_h4 = card_name_elem.find('h4')\n",
    "                if card_name_h4 is not None:\n",
    "                    card_name = card_name_h4.text.strip()\n",
    "                    print('Card Name:',card_name)\n",
    "                    print('Joining Fee:',card_join_fee)\n",
    "                    card_annual_fee = card.find('span',class_=\"line\").strong\n",
    "                    if card_annual_fee is not None:\n",
    "                        print('Annual Fee:',card_annual_fee.text)\n",
    "                        print('\\t')  \n",
    "                    else:\n",
    "                        continue\n",
    "                    # Join the benefits tags using ';' as a delimiter\n",
    "                    print('Benefits of The Card:', benefits)\n",
    "                    print('\\n\\n')\n",
    "                    # Check if the card is already in the existing data\n",
    "                    if card_name not in existing_data['Card Name'].values:\n",
    "                        new_cards.append([card_name, card_join_fee, card_annual_fee.text, benefits])\n",
    "            \n",
    "\n",
    "    # Append new cards to the existing data\n",
    "    if new_cards:\n",
    "        for new_card in new_cards:\n",
    "            sheet.append(new_card)\n",
    "\n",
    "    # Save the updated data\n",
    "    excel.save('Credit.xlsx')\n",
    "\n",
    "# Run the scraping function\n",
    "scrape_credit_cards()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "52827196",
   "metadata": {},
   "source": [
    "# all the benefits of each credit card in multiple cells of Excel sheet "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "947bf768",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['Credit Cards']\n",
      "Card Name: Platinum Credit Card\n",
      "Joining Fee: NIL\n",
      "Annual Fee: NIL\n",
      "\t\n",
      "Benefits of The Card:\n",
      "Zero Joining and Annual Fees\n",
      "2 Rewards Points per Rs. 100 spent, except Fuel\n",
      "1% Fuel Surcharge waiver at HPCL petrol pumps\n",
      "Exclusive Dinning Offers through Culinary Treats Programme\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Coral Credit Card\n",
      "Joining Fee: ₹500/ NIL\n",
      "Annual Fee: ₹500/ NIL\n",
      "\t\n",
      "Benefits of The Card:\n",
      "25% discount on movie tickets, on BookMyShow and Inox, twice per month\n",
      "Exclusive Dinning Offers through Culinary Treats Programme\n",
      "One Complimentary Railway and Domestic Airport Lounge Access, per quarter\n",
      "1% Fuel Surcharge waiver at HPCL Petrol Pumps\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Rubyx Credit Card\n",
      "Joining Fee: ₹3000+GST\n",
      "Annual Fee: ₹2000+GST\n",
      "\t\n",
      "Benefits of The Card:\n",
      "Welcome vouchers worth Rs. 5000+\n",
      "25% discount on movie tickets, on BookMyShow and Inox, twice per month\n",
      "Air Accident insurance of Rs 1 cr and lost card liability Rs 50k\n",
      "Two Complimentary rounds of golf, per month\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Sapphiro Credit Card\n",
      "Joining Fee: ₹6500+GST\n",
      "Annual Fee: ₹3500+GST\n",
      "\t\n",
      "Benefits of The Card:\n",
      "Welcome vouchers worth Rs. 9000+\n",
      "Buy one movie ticket, get Rs 500 off on second tikcet, on BookMyShow, twice per month\n",
      "Two Complimentary International Airport Lounge Access, per year\n",
      "Four Complimentary Domestic Airport Lounge Access, per quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Manchester United Platinum Credit Card\n",
      "Joining Fee: ₹499+GST\n",
      "Annual Fee: ₹499+GST\n",
      "\t\n",
      "Benefits of The Card:\n",
      "Complimentary Manchester United Football\n",
      "Up to 3 reward points per Rs. 100 spent\n",
      "25% off up to Rs. 100 on selected cinema ticket retailers\n",
      "1 Complimentary Airport Lounge Access per quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Manchester United Signature Credit Card\n",
      "Joining Fee: ₹2499+GST\n",
      "Annual Fee: ₹2499+GST/\n",
      "\t\n",
      "Benefits of The Card:\n",
      "Complimentary Manchester United Football & Holdall\n",
      "Up to 5 reward points per Rs. 100 spent\n",
      "25% off up to Rs. 150 on selected cinema ticket retailers\n",
      "Two Complimentary Airport Lounge Access/quarter\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Chennai Super Kings Credit Card\n",
      "Joining Fee: ₹500 + (GST)\n",
      "Card Name: MakeMyTrip ICICI Bank Platinum Credit Card\n",
      "Joining Fee: ₹500+Gst\n",
      "Annual Fee: Nil\n",
      "\t\n",
      "Benefits of The Card:\n",
      "Joining Fee: Rs.500+GST, Annual Fee (Second year onwards) – Nil\n",
      "Rs 500 My Cash plus MakeMyTrip holiday voucher worth Rs 3,000 as joining benefit\n",
      "1 complimentary airport lounge access per quarter and 1 complimentary railway lounge access\n",
      "\n",
      "\n",
      "\n",
      "Card Name: MakeMyTrip ICICI Bank Signature Credit Card\n",
      "Joining Fee: ₹2500+Gst\n",
      "Annual Fee: Nil\n",
      "\t\n",
      "Benefits of The Card:\n",
      " Joining Fee: Rs.2500+GST, Annual Fee (Second year onwards) – Nil\n",
      "Rs 1,500 My Cash* plus complimentary MMTBLACK Exclusive membership*, plus MakeMyTrip holiday voucher worth Rs 2,500 on joining\n",
      "Complimentary international and domestic airport lounge access# and domestic railway lounge access\n",
      "Exclusive MMT Cabs benefits\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Unifare Mumbai Metro Cards\n",
      "Joining Fee: ₹299\n",
      "Annual Fee: ₹299/\n",
      "\t\n",
      "Benefits of The Card:\n",
      "Up to 20% discount on Mumbai Metro fare\n",
      "Dual benefits of Mumbai Metro Smart Card and a Credit Card\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Unifare Delhi Metro Cards\n",
      "Joining Fee: ₹299\n",
      "Annual Fee: ₹299/\n",
      "\t\n",
      "Benefits of The Card:\n",
      "10% discount on Delhi Metro fare\n",
      "Dual benefits of a Delhi Metro Smart Card and a Credit Card\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Unifare Banglore Metro Cards\n",
      "Joining Fee: ₹299\n",
      "Annual Fee: ₹299/\n",
      "\t\n",
      "Benefits of The Card:\n",
      "15% discount on Namma Metro fare\n",
      "Dual benefits of Namma Metro Smart Card and a Credit Card\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Expressions Card\n",
      "Joining Fee: ₹499 + GST\n",
      "Annual Fee: ₹499 + GST\n",
      "\t\n",
      "Benefits of The Card:\n",
      "Earn 3 Reward Points per ₹ 100 spent for all retail purchases except fuel\n",
      "Avail of 25% discount up to INR 100 on purchase of minimum two tickets up to two times in a month\n",
      "\n",
      "\n",
      "\n",
      "Card Name: HPCL Coral Visa Card\n",
      "Joining Fee: ₹199+GST\n",
      "Annual Fee: ₹199+GST\n",
      "\t\n",
      "Benefits of The Card:\n",
      "2.5% cashback and savings of 1% fuel surcharge on fuel purchases at HPCL pumps\n",
      " Earn 2 Reward Points from ICICI Bank Rewards on every ₹100 spent on retail purchases except fuel.\n",
      "25% discount on movie ticket bookings up to Rs. 100 per transaction on BMS and Inox\n",
      "\n",
      "\n",
      "\n",
      "Card Name: HPCL Super Saver Credit Card\n",
      "Joining Fee: ₹500+GST\n",
      "Annual Fee: ₹ 500+GST\n",
      "\t\n",
      "Benefits of The Card:\n",
      "5% cashback on fuel spends at HPCL fuel pumps\n",
      "Earn 5% back (in Reward Points) on utility, grocery and departmental store spends\n",
      "Complimentary 24x7 Road-Side Assistance (RSA) services\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Emirates\n",
      "Joining Fee: ₹ 10,000+GST\n",
      "Annual Fee: ₹ 10,000+GST\n",
      "\t\n",
      "Benefits of The Card:\n",
      "Earn Skywards miles on spends\n",
      "Complimentary airport lounge access and spa sessions\n",
      "Exclusive dining offers through ICICI Bank culinary treats programme\n",
      "\n",
      "\n",
      "\n",
      "Card Name: Accelero\n",
      "Joining Fee: ₹ 499+GST\n",
      "Annual Fee: ₹ 499+GST\n",
      "\t\n",
      "Benefits of The Card:\n",
      "2 ICICI Bank  Reward points on every Rs 100 spent for retail transactions except fuel\n",
      "Complimentary 24X7 roadside assistance, with complimentary key car parts\n",
      "2.5% cashback* on your fuel purchases at HPCL petrol pumps\n",
      "1 complimentary airport lounge access per quarter by spending INR 5,000 in previous calendar quarter\n",
      "\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import openpyxl\n",
    "excel = openpyxl.Workbook()\n",
    "sheet = excel.active\n",
    "sheet.title = \"Credit Cards\"\n",
    "print(excel.sheetnames)\n",
    "sheet.append(['Card Name', 'Joining Fee', 'Annual Fee', 'Benefits of The Card'])\n",
    "\n",
    "\n",
    "source = requests.get('https://www.icicibank.com/card/credit-cards/credit-card')\n",
    "source.raise_for_status()\n",
    "soup = BeautifulSoup(source.text, 'html.parser')\n",
    "\n",
    "cards = soup.find('div', class_='compare-account account-variants-single-card').find_all('div', class_='account-variants-card-with-img')\n",
    "\n",
    "for card in cards:\n",
    "    #Find the name element for the card\n",
    "    card_name_elem = card.find('div', class_='titie-wrapper')\n",
    "    #Find the joining fee for the card\n",
    "    card_join_fee = card.find('span', class_=\"joining-fee\").strong.text\n",
    "    #finding benefits of card\n",
    "    benefits_tags = card.find('ul').find_all('li')\n",
    "    if card_name_elem is not None:\n",
    "        #Find the card name if it is in an h3 tag\n",
    "        card_name_h3 = card_name_elem.find('h3')\n",
    "        if card_name_h3 is not None:\n",
    "            card_name = card_name_h3.text.strip()\n",
    "            print('Card Name:',card_name)\n",
    "            print('Joining Fee:',card_join_fee)\n",
    "            card_annual_fee = card.find('span',class_=\"line\").strong\n",
    "            if card_annual_fee is not None:\n",
    "                print('Annual Fee:',card_annual_fee.text)\n",
    "                print('\\t')  \n",
    "            else:\n",
    "                continue\n",
    "            print('Benefits of The Card:')\n",
    "            for tag in benefits_tags:\n",
    "                print(tag.text)\n",
    "                sheet.append([card_name,card_join_fee,card_annual_fee.text,tag.text])\n",
    "            print('\\n\\n')\n",
    "        else:\n",
    "            #Find the card name if it is in an h4 tag\n",
    "            card_name_h4 = card_name_elem.find('h4')\n",
    "            if card_name_h4 is not None:\n",
    "                card_name = card_name_h4.text.strip()\n",
    "                print('Card Name:',card_name)\n",
    "                print('Joining Fee:',card_join_fee)\n",
    "                card_annual_fee = card.find('span',class_=\"line\").strong\n",
    "                if card_annual_fee is not None:\n",
    "                    print('Annual Fee:',card_annual_fee.text)\n",
    "                    print('\\t')  \n",
    "                else:\n",
    "                    continue\n",
    "                print('Benefits of The Card:')\n",
    "                for tag in benefits_tags:\n",
    "                    print(tag.text)\n",
    "                    sheet.append([card_name,card_join_fee,card_annual_fee.text,tag.text])\n",
    "                print('\\n\\n')\n",
    "    \n",
    "                \n",
    "excel.save('Credit Card Details.xlsx')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fbe506ca",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
